[env:esp32_web]
platform = espressif32
board = esp32dev
framework = arduino

build_flags = 
    -DCORE_DEBUG_LEVEL=1
    -DONEWIRE_PIN=3
    -DENABLE_PIN=4

monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    paulstoffregen/OneWire @ ^2.3.7
    bblanchon/ArduinoJson @ ^6.21.3
    ESP32Async/ESPAsyncWebServer @ ^3.0.0
