name: Build ESP32 Makita BMS Reader

on:
  workflow_dispatch: # 允许你手动触发编译
  push:             # 或者当你向main分支推送代码时自动触发
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build the firmware
        run: pio run
      - name: Upload the firmware as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware_bin
          path: .pio/build/*/firmware.bin
