name: Build ESP32 Makita BMS Reader

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build firmware
        run: pio run -e esp32_web
      - name: Upload firmware
        uses: actions/upload-artifact@v6
        with:
          name: firmware_bin
          path: .pio/build/esp32_web/firmware.bin
